Style/CombinableLoops:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 60
Metrics/ModuleLength:
  Max: 150
Metrics/BlockLength:
  IgnoredMethods: ['guard', 'loop', 'describe']
  Max: 40
Layout/LineLength:
  Max: 100
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'db/*'
  TargetRubyVersion: 3.0.0
